import {
  CrawledPost,
  MyThreadsAccount,
  PublishingTask,
  WatchlistAccount,
  EngagementPoint,
  PostFrequencyPoint,
  TrendPoint,
} from './types';

const buildFollowerTrend = (base: number): TrendPoint[] => [
  { date: '2024-12-28', value: base },
  { date: '2025-01-02', value: base + Math.round(base * 0.02) },
  { date: '2025-01-05', value: base + Math.round(base * 0.035) },
];

const buildEngagementTrend = (base: number): EngagementPoint[] => [
  { date: '2024-12-28', engagementRate: base },
  { date: '2025-01-02', engagementRate: base + 0.3 },
  { date: '2025-01-05', engagementRate: base + 0.6 },
];

const buildFrequencyTrend = (): PostFrequencyPoint[] => [
  { date: '2024-12-28', posts: 2 },
  { date: '2024-12-31', posts: 3 },
  { date: '2025-01-05', posts: 4 },
];

export const MY_THREADS_ACCOUNTS: MyThreadsAccount[] = [
  {
    id: 'my-1',
    handle: '@insightlab',
    displayName: 'Insight Lab',
    followerCount: 18400,
    timezone: 'America/New_York',
    status: 'active',
    isPrimary: true,
    lastPublishedAt: '2025-01-05T14:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=96&q=80',
  },
  {
    id: 'my-2',
    handle: '@trendwatch',
    displayName: 'Trend Watch',
    followerCount: 9200,
    timezone: 'Europe/London',
    status: 'active',
    lastPublishedAt: '2025-01-04T19:10:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?auto=format&fit=crop&w=96&q=80',
  },
  {
    id: 'my-3',
    handle: '@latebreak',
    displayName: 'Late Break',
    followerCount: 5600,
    timezone: 'America/Los_Angeles',
    status: 'paused',
    lastPublishedAt: null,
    avatarUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=96&q=80',
  },
];

export const WATCHLIST_ACCOUNTS: WatchlistAccount[] = [
  {
    id: 'wl-1',
    handle: '@urbanthreads',
    username: 'urbanthreads',
    displayName: 'Urban Threads',
    platform: 'Threads',
    category: 'Fashion & Lifestyle',
    tags: ['streetwear', 'drops', 'collabs'],
    monitoringSince: '2024-08-11T08:30:00Z',
    lastCrawledAt: '2025-01-06T13:05:00Z',
    crawlFrequency: 'Hourly',
    sentimentTrend: 'positive',
    riskLevel: 'medium',
    status: 'monitoring',
    avatarUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=96&q=80',
    followerCount: 58400,
    followerGrowth: buildFollowerTrend(56000),
    engagementRateTrend: buildEngagementTrend(4.2),
    postFrequencyTrend: buildFrequencyTrend(),
    avgEngagementRate: 4.8,
    note: 'Focus on limited drops and members-only launches.',
    watcher: { id: 'team-1', name: 'Avery Chen' },
    alerts: {
      notifyOnNewPost: true,
      notifyOnFollowerSpike: true,
      notifyOnEngagementDrop: false,
    },
    lastCrawlStatus: 'success',
    lastCrawlMessage: 'Crawl completed 1 hour ago.',
  },
  {
    id: 'wl-2',
    handle: '@nightlynews',
    username: 'nightlynews',
    displayName: 'Nightly Newsroom',
    platform: 'Threads',
    category: 'Media & Publishing',
    tags: ['breaking-news', 'analysis'],
    monitoringSince: '2024-09-02T11:15:00Z',
    lastCrawledAt: '2025-01-06T10:55:00Z',
    crawlFrequency: 'Daily',
    sentimentTrend: 'neutral',
    riskLevel: 'low',
    status: 'monitoring',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=96&q=80',
    followerCount: 91200,
    followerGrowth: buildFollowerTrend(89000),
    engagementRateTrend: buildEngagementTrend(3.1),
    postFrequencyTrend: buildFrequencyTrend(),
    avgEngagementRate: 3.4,
    note: 'Monitor for late-night breaking updates.',
    watcher: { id: 'team-2', name: 'Jonah Patel' },
    alerts: {
      notifyOnNewPost: true,
      notifyOnFollowerSpike: false,
      notifyOnEngagementDrop: false,
    },
    lastCrawlStatus: 'scheduled',
    lastCrawlMessage: 'Next crawl queued for 15 minutes from now.',
  },
  {
    id: 'wl-3',
    handle: '@studioflux',
    username: 'studioflux',
    displayName: 'Studio Flux',
    platform: 'Instagram',
    category: 'Creative Agencies',
    tags: ['campaigns', 'motion'],
    monitoringSince: '2024-10-21T09:20:00Z',
    lastCrawledAt: '2025-01-05T22:12:00Z',
    crawlFrequency: 'Hourly',
    sentimentTrend: 'positive',
    riskLevel: 'high',
    status: 'monitoring',
    avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=96&q=80',
    followerCount: 48200,
    followerGrowth: buildFollowerTrend(46000),
    engagementRateTrend: buildEngagementTrend(5.1),
    postFrequencyTrend: buildFrequencyTrend(),
    avgEngagementRate: 5.6,
    note: 'Creative shop with high production value reels.',
    watcher: { id: 'team-3', name: 'Leah Ortiz' },
    alerts: {
      notifyOnNewPost: true,
      notifyOnFollowerSpike: true,
      notifyOnEngagementDrop: true,
    },
    lastCrawlStatus: 'success',
    lastCrawlMessage: 'Last crawl surfaced 3 new videos.',
  },
  {
    id: 'wl-4',
    handle: '@socialnorth',
    username: 'socialnorth',
    displayName: 'Social North',
    platform: 'Threads',
    category: 'Media & Publishing',
    tags: ['community', 'interviews'],
    monitoringSince: '2024-11-09T18:05:00Z',
    lastCrawledAt: '2025-01-06T05:35:00Z',
    crawlFrequency: 'Daily',
    sentimentTrend: 'negative',
    riskLevel: 'medium',
    status: 'monitoring',
    avatarUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=96&q=80',
    followerCount: 37800,
    followerGrowth: buildFollowerTrend(36000),
    engagementRateTrend: buildEngagementTrend(2.8),
    postFrequencyTrend: buildFrequencyTrend(),
    avgEngagementRate: 2.5,
    note: 'Community account seeing sentiment swings.',
    watcher: null,
    alerts: {
      notifyOnNewPost: false,
      notifyOnFollowerSpike: true,
      notifyOnEngagementDrop: true,
    },
    lastCrawlStatus: 'failed',
    lastCrawlMessage: 'Authentication error during previous crawl.',
  },
  {
    id: 'wl-5',
    handle: '@creatorlab',
    username: 'creatorlab',
    displayName: 'Creator Lab',
    platform: 'TikTok',
    category: 'Creators & Influencers',
    tags: ['tutorials', 'trends'],
    monitoringSince: '2024-07-14T16:45:00Z',
    lastCrawledAt: '2025-01-05T16:48:00Z',
    crawlFrequency: 'Weekly',
    sentimentTrend: 'positive',
    riskLevel: 'low',
    status: 'paused',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=96&q=80',
    followerCount: 74200,
    followerGrowth: buildFollowerTrend(72000),
    engagementRateTrend: buildEngagementTrend(6.2),
    postFrequencyTrend: buildFrequencyTrend(),
    avgEngagementRate: 6.5,
    note: 'Paused while evaluating collab potential.',
    watcher: { id: 'team-4', name: 'Mira Davenport' },
    alerts: {
      notifyOnNewPost: false,
      notifyOnFollowerSpike: false,
      notifyOnEngagementDrop: false,
    },
    lastCrawlStatus: 'running',
    lastCrawlMessage: 'Manual sync kicked off 5 minutes ago.',
  },
];

export const CRAWLED_POSTS: CrawledPost[] = [
  {
    id: 'post-1',
    watchlistAccountId: 'wl-1',
    content:
      'New capsule drop tonight. Limited to 200 units with hand-stitched detailing. Members get early access at 7pm ET.',
    capturedAt: '2025-01-06T12:55:00Z',
    language: 'en',
    topics: ['product-launch', 'streetwear'],
    mediaType: 'image',
    images: [
      {
        src: 'https://images.unsplash.com/photo-1525171254930-643fc658b64e?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1525171254930-643fc658b64e?auto=format&fit=crop&w=1200&q=90',
        alt: 'Streetwear jacket flatlay',
      },
      {
        src: 'https://images.unsplash.com/photo-1529336953121-497f6c1ed5f0?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1529336953121-497f6c1ed5f0?auto=format&fit=crop&w=1200&q=90',
        alt: 'Minimal sneakers',
      },
      {
        src: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=90',
        alt: 'Close up of fabric texture',
      },
    ],
    status: 'ready',
    sentiment: 'positive',
    likes: 1850,
    replies: 240,
    reposts: 310,
  },
  {
    id: 'post-2',
    watchlistAccountId: 'wl-1',
    content:
      'We just opened applications for our creator residency. Looking for photographers and stylists focused on sustainability.',
    capturedAt: '2025-01-06T08:10:00Z',
    language: 'en',
    topics: ['community', 'creator-program'],
    mediaType: 'text',
    status: 'draft',
    sentiment: 'neutral',
    likes: 430,
    replies: 52,
    reposts: 28,
  },
  {
    id: 'post-3',
    watchlistAccountId: 'wl-2',
    content:
      'Tonight on Nightly Newsroom: a deep dive into how small publishers are using AI for weekend coverage. Thread goes live at 9pm ET.',
    capturedAt: '2025-01-05T23:40:00Z',
    language: 'en',
    topics: ['ai', 'media-trends'],
    mediaType: 'video',
    videos: [
      {
        src: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1525182008055-f88b95ff7980?auto=format&fit=crop&w=320&q=60',
        title: 'AI deep dive teaser',
      },
      {
        src: 'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=320&q=60',
        title: 'Publisher interview snippet',
      },
    ],
    status: 'ready',
    sentiment: 'positive',
    likes: 980,
    replies: 190,
    reposts: 145,
  },
  {
    id: 'post-4',
    watchlistAccountId: 'wl-3',
    content:
      'Studio Flux is premiering the "No Color" campaign for Futura Denim with an interactive takeover next week. Sneak peek shots inside.',
    capturedAt: '2025-01-05T18:22:00Z',
    language: 'en',
    topics: ['campaign', 'client-work'],
    mediaType: 'video',
    videos: [
      {
        src: 'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=320&q=60',
        title: 'Campaign teaser',
      },
      {
        src: 'https://storage.googleapis.com/coverr-main/mp4/Nature.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=320&q=60',
        title: 'Behind the scenes',
      },
    ],
    status: 'ready',
    sentiment: 'positive',
    likes: 1630,
    replies: 205,
    reposts: 276,
  },
  {
    id: 'post-5',
    watchlistAccountId: 'wl-4',
    content:
      'Our community sessions are shifting to Wednesday mornings this quarter. Drop your questions for our upcoming guest editors.',
    capturedAt: '2025-01-04T15:42:00Z',
    language: 'en',
    topics: ['community', 'events'],
    mediaType: 'text',
    images: [
      {
        src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=90',
        alt: 'Community meetup',
      },
    ],
    status: 'scheduled',
    scheduledFor: '2025-01-07T15:00:00Z',
    targetAccountId: 'my-2',
    sentiment: 'neutral',
    likes: 520,
    replies: 63,
    reposts: 41,
  },
  {
    id: 'post-6',
    watchlistAccountId: 'wl-4',
    content:
      'Interview lineup confirmed for Q1 featuring founders from the Nordic media scene. Submissions now open for audience questions.',
    capturedAt: '2025-01-03T19:55:00Z',
    language: 'en',
    topics: ['interviews', 'community'],
    mediaType: 'text',
    images: [
      {
        src: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=90',
        alt: 'Interview microphone',
      },
      {
        src: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=240&q=60',
        full: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=90',
        alt: 'Podcast studio',
      },
    ],
    status: 'published',
    publishedAt: '2025-01-04T20:30:00Z',
    targetAccountId: 'my-1',
    sentiment: 'positive',
    likes: 810,
    replies: 120,
    reposts: 99,
  },
];

export const PUBLISHING_TASKS: PublishingTask[] = [
  {
    id: 'task-1',
    postId: 'post-5',
    watchlistAccountId: 'wl-4',
    targetAccountId: 'my-2',
    action: 'schedule',
    status: 'scheduled',
    scheduledFor: '2025-01-07T15:00:00Z',
    notes: 'Queue with weekly community digest.',
  },
  {
    id: 'task-2',
    postId: 'post-6',
    watchlistAccountId: 'wl-4',
    targetAccountId: 'my-1',
    action: 'publish',
    status: 'completed',
    executedAt: '2025-01-04T20:30:00Z',
    notes: 'Repurposed with CTA to join newsletter.',
  },
];
